language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: jQljbjk+u4Io0kDvyMSmcEsKKalmi2hdjUVmLwZPSOusIpwjP/H+o2uGTEsz0FGJ2CCmtVIkxoHIDYstAD0F8ZMDTni8M60It9y5hGONp6Q6lOeLyjXzjOlfjizj/NQwr1ZcslNzauNxyDdW7ts0Qhx22omLFSKaFh9XkF2Hzs3RlF6G/t3sYkppY6eY5T7Boe7O+k2G95eO5XMVJPqweNmjdB+Bxj07aJqXljgKrVGiYhjwyALy3yDmC8DGlotALoVYCb0TV3jyt9RtOObXH2dpVqZKdYBH622Tt32gpFo0/2649TEWkPG8i51o5+EVppsG3LXqyPYr7fiX6/sbs7C+1a4wyQ7vbG7Kz970qFMuaIxtIAqTdbmLnJMQlN5mG4BzzeibatAeNf/asIq3Db6GeSHK8yG+Fr09V7fxZmICZZTX4orrLKx//IAaSCE9Yj7kvifC629pmAjsFP3IV3L9Nwj/1jG7Hh1E3DX0Rb7l2agDSMnEeyj8JLhd3XmYkSPuaoH7fskNWTXt4NqnuvqtGANMNme5XjptPkvCj1OgaEZqS4fXYS7307CSg60HAP6on/dD1AjMdOJO9fMvLvizArtuqsa/ei1MkRbX5HUO5R4J+yYfRZr84z0+6c3qqOXnF8Jic2KD6LqjH4jOtBdCypn7s4cUij3AOkZ1fPc=
  app: c475-kyl116
